pr1: Updated README.md
manikandan-kumaresan/ODBC-Jira pull request #1
Opened 2019-12-06 09:43 UTC by manikandan-kumaresan

Added feature

2019-12-06 10:29 UTC, manikandan-kumaresan commented
review comment1

2019-12-06 10:30 UTC, manikandan-kumaresan commented
> Added feature

what feature

2019-12-11 09:33 UTC, syncuser123 commented
Code changes reviewed. No concerns

2019-12-11 09:38 UTC, syncuser123 requested changes

2019-12-11 09:38 UTC, syncuser123 commented on README.md
> +Feature added
What feature

2019-12-11 09:39 UTC, manikandan-kumaresan commented on README.md
> +Feature added
Test dummy feature1

2019-12-11 09:39 UTC, merged